name: Continuous Integration Continuous Deployment

on:
  push:
    branches: [ feature/*, main, dev, release]
  pull_request:
    branches: [ main, dev, release ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Branch name policy
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,release,hotfix,fix' # All branches should start with the given prefix
          ignore: main,dev # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 100 # Max length of the branch name
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Build for Development
        if: startsWith(github.ref, 'refs/heads/dev')
        run: npm run build:dev
      - name: Build for QA
        if: startsWith(github.ref, 'refs/heads/release/')
        run: npm run build:qa
      - name: Build for Production
        if: startsWith(github.ref, 'refs/heads/main')
        run: npm run build:prod
      - name: Archive Build Artifact
        if: startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/main')
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
          
  deploy:
    needs: [build]
    name: Deploy
    if: startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Development
        if: startsWith(github.ref, 'refs/heads/dev')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:darts-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to QA
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:darts-qa
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Production
        if: startsWith(github.ref, 'refs/heads/main')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:darts-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}