name: Continuous Integration Continuous Deployment

on:
  push:
    branches: [ feature/*, main, dev, release]
  pull_request:
    branches: [ main, dev, release ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Branch name policy
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,release,hotfix,fix' # All branches should start with the given prefix
          ignore: main,dev # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 100 # Max length of the branch name
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm run test:ci
      - name: Run versioning scripts
        run: node ./scripts/test-pipeline.js --branch $GITHUB_REF
      - name: Build
        run: npm run build
  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        if: startsWith(github.ref, 'refs/heads/dev')
        with:
          args: deploy --only hosting:darts-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          args: deploy --only hosting:darts-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}